<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG83LVAG\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG83LVAG/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG83LVAG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG83LVAG\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG83LVAG\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G83LVAG',
    'container.build_id' => 'fddfcdcb',
    'container.build_time' => 1611572796,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG83LVAG');
