<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM2Mld9Q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM2Mld9Q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM2Mld9Q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM2Mld9Q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM2Mld9Q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M2Mld9Q',
    'container.build_id' => 'e03fc0b6',
    'container.build_time' => 1611315717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM2Mld9Q');
